services:
    # основное приложение с fpm, все остальные (шедулер, очереди, октан) используют его image
    app:
        build:
            args:
                user: www
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - db
            - app-setup
        volumes:
            - ../src/:/var/www
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # запуск команд, необходимых для работы приложение - установка пакетов композера, применение миграций и т.д.
    app-setup:
        image: laravel-app
        pull_policy: never
        container_name: app-setup
        restart: no
        tty: true
        working_dir: /var/www/
        depends_on:
            - db
        volumes:
            - ../src/:/var/www
        command:
            - /bin/sh
            - -c
            - |
                composer install
                php artisan migrate --force
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # копия приложения, запущенная на октане
    app-octane:
        image: laravel-app
        pull_policy: never
        container_name: app-octane
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        entrypoint: php artisan octane:start --port=8081 --workers=${APP_OCTANE_WORKERS:-4} -n
        expose:
            - 8081
        depends_on:
            - app-setup
            - db
        volumes:
            - ../src/:/var/www
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # шедулер
    app-scheduler-worker:
        image: laravel-app
        pull_policy: never
        container_name: app-scheduler-worker
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        entrypoint: php artisan schedule:work
        depends_on:
            - app-setup
            - db
        volumes:
            - ../src/:/var/www
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # очереди
    app-queue-default-worker:
        image: laravel-app
        pull_policy: never
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        entrypoint: php artisan queue:work --queue=default --max-time=1800 --timeout=3600
        deploy:
            mode: replicated
            replicas: ${LARAVEL_QUEUE_DEFAULT_WORKERS:-1}
        depends_on:
            - app-setup
            - db
        volumes:
            - ../src/:/var/www
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # база данных
    db:
        image: postgres:17.2
        container_name: db-app
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # админка для базы
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:8.13
        restart: unless-stopped
        environment:
            PGADMIN_CONFIG_SERVER_MODE: "False"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "5050:80"
        profiles:
            - dev
        networks:
            - app-network

    # nginx, раздает статику, проксирует запросы на fpm и октан
    nginx:
        image: nginx:alpine
        container_name: app-webserver
        restart: unless-stopped
        ports:
            - "${APP_PORT:-8180}:80"
            - "${APP_OCTANE_PORT:-8080}:8080"
        volumes:
            - ../src/:/var/www
            - ./config/nginx/conf.d:/etc/nginx/conf.d/
        healthcheck:
            test: curl -f http://localhost/up || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        profiles:
            - dev
            - prod
        networks:
            - app-network

    # фронт
    frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        container_name: frontend
        restart: always
        working_dir: /app
        command:
            - /bin/sh
            - -c
            - |
               bun install
               bunx vite --host=0.0.0.0
        volumes:
            - ../frontend:/app
        ports:
            - "${VITE_PORT:-5173}:5173"
        profiles:
            - dev
        networks:
            - app-network
networks:
    app-network:
      driver: bridge
