name: test

on: push

env:
    POSTGRES_DB: app
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
    VITE_API_BASE_URL: http://nginx/api

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Copy env
              run: |
                cp ./src/.env.testing ./src/.env

            - name: Docker compose up
              run: |
                cd docker
                docker compose --profile test up --build -d
                docker compose exec -it app php artisan dusk:chrome-driver --detect
                docker compose exec -it app php artisan dusk
