name: test

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Docker compose up
              run: |
                cd docker
                docker compose --profile test up --build -d

            - name: Prepare dusk
              run: |
                cd docker
                docker compose exec app php artisan dusk:chrome-driver --detect

            - name: Dusk test
              run: |
                cd docker
                docker compose exec app php artisan dusk
